<?php

//namespace console\migrations;

use yii\db\Migration;

/**
 * Class M181015114459Multiple_task_assignees
 */
class M181015114459Multiple_task_assignees extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
		//create task_assigned_user table 
		$this->createTable("{{%task_assigned_user}}", [
										'id' => $this->primaryKey(11),
										'task_id' => $this->integer(11),
										'user_id' => $this->integer(11),
										'assigned_date' => $this->dateTime()
																	->comment('Add an autogenerated dateTime for the moment the task was assigned'),
							]);
		// creates task_assigned_user table index for task_id
        $this->createIndex(
            'idx-task_assigned_user-task_id',
            "{{%task_assigned_user}}",
            'task_id'
        );
		// creates task_assigned_user table index for user_id
        $this->createIndex(
            'idx-task_assigned_user-user_id',
            "{{%task_assigned_user}}",
            'user_id'
        );
		// add task_assigned_user table foreign key to table `task`
        $this->addForeignKey(
            'TaskItem',
            "{{%task_assigned_user}}",
            'task_id',
            "{{%task}}",
            'id',
            'CASCADE'
        );
		// add task_assigned_user table foreign key to table `user`
        $this->addForeignKey(
            'UserAssignee',
            "{{%task_assigned_user}}",
            'user_id',
            "{{%user}}",
            'id',
            'CASCADE'
        );
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "M181015114459Multiple_task_assignees should not be reverted.\n";
		$this->dropForeignKey('TaskItem', "{{%task_assigned_user}}");
		$this->dropIndex('idx-task_assigned_user-task_id', "{{%task_assigned_user}}");
		$this->dropForeignKey('UserAssignee', "{{%task_assigned_user}}");
		$this->dropIndex('idx-task_assigned_user-user_id', "{{%task_assigned_user}}");
		$this->dropTable("{{%task_assigned_user}}");
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "M181015114459Multiple_task_assignees cannot be reverted.\n";

        return false;
    }
    */
}
