<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%task_assigned_user}}".
 *
 * @property int $id
 * @property int $task_id
 * @property int $user_id
 * @property string $assigned_date Add an autogenerated dateTime for the moment the task was assigned
 *
 * @property Task $task
 * @property User $user
 */
class TaskAssignedUser extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%task_assigned_user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['task_id', 'user_id'], 'integer'],
            [['assigned_date'], 'safe'],
            [['task_id'], 'exist', 'skipOnError' => true, 'targetClass' => Task::className(), 'targetAttribute' => ['task_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserDb::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'task_id' => 'Task ID',
            'user_id' => 'User ID',
            'assigned_date' => 'Assigned Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTask()
    {
        return $this->hasOne(Task::className(), ['id' => 'task_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function taskAssignee($user, $userDb, $task, $status)
    {
        $userModel = $userDb->findOne($user);
        $person = $userModel->fullName;
        $username = $userModel->username;
        $image = $userModel->profile_image;
        return json_encode([$user, $task, $person, $username, $image, $status]);
    }

    public function taskApiAssignees($user, $userDb, $task, $status, $id, $date)
    {
        $userModel = $userDb->findOne($user);
        $person = $userModel->fullName;
        $username = $userModel->username;
        $image = $userModel->profile_image;
        $assignee['id'] = $id;
        $assignee['task_id'] = $task;
        $assignee['user_id'] = $user;
        $assignee['assigned_date'] = $date;
        $assignee['name'] = $person;
        $assignee['profile_image'] = !empty($image)?'http://ubuxa.net/'.$image : 'http://ubuxa.net/images/users/default-user.png';;
        $assignee['status'] = $status;
        return [$assignee];
    }

}
