<?php
return [
    'create:Correspondence' => [
        'type' => 2,
        'description' => 'Permit Create on Correspondence items.',
    ],
    'admin' => [
        'type' => 1,
        'children' => [
            'create:Correspondence',
            'create:EDocument',
            'create:Folder',
            'create:Invoice',
            'create:Order',
            'create:Payment',
            'create:Project',
            'create:Site',
            'create:User',
            'delete:Correspondence',
            'delete:EDocument',
            'delete:Folder',
            'delete:Invoice',
            'delete:Order',
            'delete:Payment',
            'delete:Project',
            'delete:Site',
            'delete:User',
            'index:Correspondence',
            'index:EDocument',
            'index:Folder',
            'index:Invoice',
            'index:Order',
            'index:Payment',
            'index:Project',
            'index:Site',
            'index:User',
            'update:Correspondence',
            'update:EDocument',
            'update:Folder',
            'update:Invoice',
            'update:Order',
            'update:Payment',
            'update:Project',
            'update:Site',
            'update:User',
            'view:Correspondence',
            'view:EDocument',
            'view:Folder',
            'view:Invoice',
            'view:Order',
            'view:Payment',
            'view:Project',
            'view:Site',
            'view:User',
        ],
    ],
    'manager' => [
        'type' => 1,
        'children' => [
            'create:Correspondence',
            'create:EDocument',
            'create:Folder',
            'create:Invoice',
            'create:Order',
            'create:Payment',
            'create:Project',
            'create:Site',
            'create:User',
            'delete:Correspondence',
            'delete:EDocument',
            'delete:Folder',
            'delete:Invoice',
            'delete:Order',
            'delete:Payment',
            'delete:Project',
            'delete:Site',
            'delete:User',
            'index:Correspondence',
            'index:EDocument',
            'index:Folder',
            'index:Invoice',
            'index:Order',
            'index:Payment',
            'index:Project',
            'index:Site',
            'index:User',
            'update:Correspondence',
            'update:EDocument',
            'update:Folder',
            'update:Invoice',
            'update:Order',
            'update:Payment',
            'update:Project',
            'update:Site',
            'update:User',
            'view:Correspondence',
            'view:EDocument',
            'view:Folder',
            'view:Invoice',
            'view:Order',
            'view:Payment',
            'view:Project',
            'view:Site',
            'view:User',
        ],
    ],
    'administrator' => [
        'type' => 1,
        'children' => [
            'create:Correspondence',
            'create:EDocument',
            'create:Folder',
            'create:Invoice',
            'create:Order',
            'create:Payment',
            'create:Project',
            'create:Site',
            'create:User',
            'index:Correspondence',
            'index:EDocument',
            'index:Folder',
            'index:Invoice',
            'index:Order',
            'index:Payment',
            'index:Project',
            'index:Site',
            'index:User',
            'update:Correspondence',
            'update:EDocument',
            'update:Folder',
            'update:Invoice',
            'update:Order',
            'update:Payment',
            'update:Project',
            'update:Site',
            'update:User',
            'view:Correspondence',
            'view:EDocument',
            'view:Folder',
            'view:Invoice',
            'view:Order',
            'view:Payment',
            'view:Project',
            'view:Site',
            'view:User',
        ],
    ],
    'field_officer' => [
        'type' => 1,
        'children' => [
            'index:Correspondence',
            'index:EDocument',
            'index:Folder',
            'index:Invoice',
            'index:Order',
            'index:Payment',
            'index:Project',
            'index:Site',
            'index:User',
            'update:Correspondence',
            'update:EDocument',
            'update:Folder',
            'update:Invoice',
            'update:Order',
            'update:Payment',
            'update:Project',
            'update:Site',
            'update:User',
            'view:Correspondence',
            'view:EDocument',
            'view:Folder',
            'view:Invoice',
            'view:Order',
            'view:Payment',
            'view:Project',
            'view:Site',
            'view:User',
        ],
    ],
    'data_entry' => [
        'type' => 1,
        'children' => [
            'create:Correspondence',
            'create:EDocument',
            'create:Folder',
            'create:Invoice',
            'create:Order',
            'create:Payment',
            'create:Project',
            'create:Site',
            'create:User',
            'index:Correspondence',
            'index:EDocument',
            'index:Folder',
            'index:Invoice',
            'index:Order',
            'index:Payment',
            'index:Project',
            'index:Site',
            'index:User',
            'view:Correspondence',
            'view:EDocument',
            'view:Folder',
            'view:Invoice',
            'view:Order',
            'view:Payment',
            'view:Project',
            'view:Site',
            'view:User',
        ],
    ],
    'create:EDocument' => [
        'type' => 2,
        'description' => 'Permit Create on EDocument items.',
    ],
    'create:Folder' => [
        'type' => 2,
        'description' => 'Permit Create on Folder items.',
    ],
    'create:Invoice' => [
        'type' => 2,
        'description' => 'Permit Create on Invoice items.',
    ],
    'create:Order' => [
        'type' => 2,
        'description' => 'Permit Create on Order items.',
    ],
    'create:Payment' => [
        'type' => 2,
        'description' => 'Permit Create on Payment items.',
    ],
    'create:Project' => [
        'type' => 2,
        'description' => 'Permit Create on Project items.',
    ],
    'create:Site' => [
        'type' => 2,
        'description' => 'Permit Create on Site items.',
    ],
    'create:User' => [
        'type' => 2,
        'description' => 'Permit Create on User items.',
    ],
    'delete:Correspondence' => [
        'type' => 2,
        'description' => 'Permit Delete on Correspondence items.',
    ],
    'delete:EDocument' => [
        'type' => 2,
        'description' => 'Permit Delete on EDocument items.',
    ],
    'delete:Folder' => [
        'type' => 2,
        'description' => 'Permit Delete on Folder items.',
    ],
    'delete:Invoice' => [
        'type' => 2,
        'description' => 'Permit Delete on Invoice items.',
    ],
    'delete:Order' => [
        'type' => 2,
        'description' => 'Permit Delete on Order items.',
    ],
    'delete:Payment' => [
        'type' => 2,
        'description' => 'Permit Delete on Payment items.',
    ],
    'delete:Project' => [
        'type' => 2,
        'description' => 'Permit Delete on Project items.',
    ],
    'delete:Site' => [
        'type' => 2,
        'description' => 'Permit Delete on Site items.',
    ],
    'delete:User' => [
        'type' => 2,
        'description' => 'Permit Delete on User items.',
    ],
    'index:Correspondence' => [
        'type' => 2,
        'description' => 'Permit Index on Correspondence items.',
    ],
    'index:EDocument' => [
        'type' => 2,
        'description' => 'Permit Index on EDocument items.',
    ],
    'index:Folder' => [
        'type' => 2,
        'description' => 'Permit Index on Folder items.',
    ],
    'index:Invoice' => [
        'type' => 2,
        'description' => 'Permit Index on Invoice items.',
    ],
    'index:Order' => [
        'type' => 2,
        'description' => 'Permit Index on Order items.',
    ],
    'index:Payment' => [
        'type' => 2,
        'description' => 'Permit Index on Payment items.',
    ],
    'index:Project' => [
        'type' => 2,
        'description' => 'Permit Index on Project items.',
    ],
    'index:Site' => [
        'type' => 2,
        'description' => 'Permit Index on Site items.',
    ],
    'index:User' => [
        'type' => 2,
        'description' => 'Permit Index on User items.',
    ],
    'see_all:Correspondence' => [
        'type' => 2,
        'description' => 'Permit See_all on Correspondence items.',
    ],
    'see_all:EDocument' => [
        'type' => 2,
        'description' => 'Permit See_all on EDocument items.',
    ],
    'see_all:Folder' => [
        'type' => 2,
        'description' => 'Permit See_all on Folder items.',
    ],
    'see_all:Invoice' => [
        'type' => 2,
        'description' => 'Permit See_all on Invoice items.',
    ],
    'see_all:Order' => [
        'type' => 2,
        'description' => 'Permit See_all on Order items.',
    ],
    'see_all:Payment' => [
        'type' => 2,
        'description' => 'Permit See_all on Payment items.',
    ],
    'see_all:Project' => [
        'type' => 2,
        'description' => 'Permit See_all on Project items.',
    ],
    'see_all:Site' => [
        'type' => 2,
        'description' => 'Permit See_all on Site items.',
    ],
    'see_all:User' => [
        'type' => 2,
        'description' => 'Permit See_all on User items.',
    ],
    'update:Correspondence' => [
        'type' => 2,
        'description' => 'Permit Update on Correspondence items.',
    ],
    'update:EDocument' => [
        'type' => 2,
        'description' => 'Permit Update on EDocument items.',
    ],
    'update:Folder' => [
        'type' => 2,
        'description' => 'Permit Update on Folder items.',
    ],
    'update:Invoice' => [
        'type' => 2,
        'description' => 'Permit Update on Invoice items.',
    ],
    'update:Order' => [
        'type' => 2,
        'description' => 'Permit Update on Order items.',
    ],
    'update:Payment' => [
        'type' => 2,
        'description' => 'Permit Update on Payment items.',
    ],
    'update:Project' => [
        'type' => 2,
        'description' => 'Permit Update on Project items.',
    ],
    'update:Site' => [
        'type' => 2,
        'description' => 'Permit Update on Site items.',
    ],
    'update:User' => [
        'type' => 2,
        'description' => 'Permit Update on User items.',
    ],
    'view:Correspondence' => [
        'type' => 2,
        'description' => 'Permit View on Correspondence items.',
    ],
    'view:EDocument' => [
        'type' => 2,
        'description' => 'Permit View on EDocument items.',
    ],
    'view:Folder' => [
        'type' => 2,
        'description' => 'Permit View on Folder items.',
    ],
    'view:Invoice' => [
        'type' => 2,
        'description' => 'Permit View on Invoice items.',
    ],
    'view:Order' => [
        'type' => 2,
        'description' => 'Permit View on Order items.',
    ],
    'view:Payment' => [
        'type' => 2,
        'description' => 'Permit View on Payment items.',
    ],
    'view:Project' => [
        'type' => 2,
        'description' => 'Permit View on Project items.',
    ],
    'view:Site' => [
        'type' => 2,
        'description' => 'Permit View on Site items.',
    ],
    'view:User' => [
        'type' => 2,
        'description' => 'Permit View on User items.',
    ],
];
